network/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = "network"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:page_number>", views.index,),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("following", views.following_page, name="following"),
    path("following/<int:page_number>", views.following_page, name="following"),
    path("profile/<str:username>", views.profile_page, name="profile"),
    path("profile/<str:username>/<int:page_number>", views.profile_page, name="profile"),
    path("update-post/<int:id>/<str:content>", views.update_post, name="update-post"),
    path("update-like/<int:id>/<str:value>", views.update_like, name="update-like"),
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    followers = models.ManyToManyField('self', blank=True, symmetrical=False)
    following = models.ManyToManyField('self', blank=True, symmetrical=False, related_name="followed_by")

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    content = models.TextField(max_length=512)
    date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User)

network/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.forms import ModelForm, Textarea, HiddenInput
from .models import User, Post
from django.db.models import Count
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator


def index(request, page_number=1):

    # Create new form by using the Post model
    class PostForm(ModelForm):
        class Meta:
            model = Post
            fields = ['content', 'user']
            labels = {
                'content': 'New Post'
            }
            widgets = {
                'content': Textarea(attrs={'class': 'form-control', 'rows': 2}),
                'user': HiddenInput
            }

    # Instantiate and save new post form
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/")

    # Initialize the 'user' field with the current user
    else:
        form = PostForm(initial={"user": request.user})

    # Retrieve all posts and save them in a list, in reverse chronological order
    posts = Post.objects.all()
    posts = posts[::-1]

    p = Paginator(posts, 10)
    current_page = p.page(page_number)
    page_posts = current_page.object_list

    return render(request, "network/index.html", {
        "form": form,
        "posts": page_posts,
        "num_pages": p.num_pages,
        "current_page": current_page,
        "has_next": current_page.has_next(),
        "has_prev": current_page.has_previous(),
        "next_num": current_page.next_page_number,
        "prev_num": current_page.previous_page_number,
        "p": p
    })

@csrf_exempt
def profile_page(request, username, page_number=1):

    # Determine the user who owns this profile
    profile_owner = User.objects.get(username=username)

    # Check if user who's visiting this page is in the followers field of profile_owner
    if request.user in profile_owner.followers.all():
        isFollower = True
    else:
        isFollower = False

    # Implement the ability to Follow or Unfollow
    if request.method == "POST":
        if not isFollower:
            profile_owner.followers.add(request.user)
            request.user.following.add(profile_owner)
        else:
            profile_owner.followers.remove(request.user)
            request.user.following.remove(profile_owner)

    # Get current number of followers and following
    followers = profile_owner.followers.aggregate(Count("id"))
    following = profile_owner.following.aggregate(Count("id"))

    # Retrieve all user posts and save them in a list
    posts = profile_owner.posts.all()
    posts = posts[::-1]

    p = Paginator(posts, 10)
    current_page = p.page(page_number)
    page_posts = current_page.object_list

    return render(request, "network/profile.html", {
        "owner": str(profile_owner.username),
        "visitor": str(request.user),
        "followers": followers["id__count"],
        "following": following["id__count"],
        "posts": page_posts,
        "num_pages": p.num_pages,
        "current_page": current_page,
        "has_next": current_page.has_next(),
        "has_prev": current_page.has_previous(),
        "next_num": current_page.next_page_number,
        "prev_num": current_page.previous_page_number,
        "p": p,
        "isFollower": isFollower
    })


def following_page(request, page_number=1):

    visitor = request.user

    # Retrieve following users' posts and store them in a list
    posts = []
    for user in visitor.following.all():
        for post in user.posts.all():
            posts.append(post)

    p = Paginator(posts, 10)
    current_page = p.page(page_number)
    page_posts = current_page.object_list

    return render(request, "network/following.html", {
        "posts": page_posts,
        "num_pages": p.num_pages,
        "current_page": current_page,
        "has_next": current_page.has_next(),
        "has_prev": current_page.has_previous(),
        "next_num": current_page.next_page_number,
        "prev_num": current_page.previous_page_number,
        "p": p,
    })

@csrf_exempt
def update_post(request, id, content):
    if request.method == "POST":
        
        # Get the post that's edited, update and save it
        post = Post.objects.get(id=id)
        post.content = content
        post.save(update_fields=['content'])

    else:
        return HttpResponseRedirect("network:index")

@csrf_exempt
def update_like(request, id, value):
    if request.method == "POST":

        # Get the post that's liked/unliked, update and save it
        if value == "Unlike":
            Post.objects.get(id=id).likes.remove(request.user)
        else:
            Post.objects.get(id=id).likes.add(request.user)

    else:
        return HttpResponseRedirect("network:index")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:
        return render(request, "network/register.html")

network/templates/network/following.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}
    {% if user.is_authenticated %}
        <h1 style="font-size: 36px;">Following Posts</h1><hr>

        {% for post in posts %}
            <div class="posts" style="position: relative;">
                <a href="{% url 'network:profile' post.user %}">{{ post.user }}</a>
                <hr style="margin-top: 0; width: 20%; position: relative; margin-left: 0px;">
                <p class="post-content">{{ post.content }}</p>
                <small>{{ post.date }}</small><br>
                <small><span class="post-likes">{{ post.likes.all.count }}</span> Likes</small><br>

                {% if user in post.likes.all %}
                    <input class="btn btn-primary likeBtn" type="submit" value="Unlike" style="border-radius: 16px;">
                {% else %}
                    <input class="btn btn-primary likeBtn" type="submit" value="Like" style="border-radius: 16px;">
                {% endif %}

                <input type="hidden" class="post-id" value="{{ post.id }}">
            </div>
        {% endfor %}

        <nav aria-label="Posts navigation" style="margin-top: 20px;">
            <ul class="pagination justify-content-center">
                {% if has_prev %}
                    <li class="page-item"><a class="page-link" href="{{ prev_num }}">Previous</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#" aria-disabled="true">Previous</a></li>
                {% endif %}
                {% for i in p.page_range %}
                    <li class="page-item"><a class="page-link" href="\following/{{i}}">{{i}}</a></li>
                {% endfor %}
                {% if has_next %}
                    <li class="page-item"><a class="page-link" href="{{ next_num }}">Next</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#" aria-disabled="true">Next</a></li>
                {% endif %}
            </ul>
        </nav>

    {% endif %}
    <script src="{% static 'network/posts-index.js' %}"></script>
{% endblock %}

network/templates/network/index.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}

    <h1 style="font-size: 36px;">All Posts</h1><hr>

    {% if user.is_authenticated %}
        <form action="" method="post">
            <div class="mb-2" style="margin: auto 20px auto 20px;">
            {% csrf_token %}
            {{ form }}
            <input class="btn btn-primary" type="submit" value="Post" style="margin-top: 10px;">
            </div>
        </form><hr>
    {% endif %}

    {% for post in posts %}
        <div class="posts" style="position: relative;">
            <a href="{% url 'network:profile' post.user %}">{{ post.user }}</a>
            <hr style="margin-top: 0; width: 20%; position: relative; margin-left: 0px;">
            <p class="post-content">{{ post.content }}</p>
            <small>{{ post.date }}</small><br>
            <small><span class="post-likes">{{ post.likes.all.count }}</span> Likes</small><br>

            {% if user in post.likes.all %}
                <input class="btn btn-primary likeBtn" type="submit" value="Unlike" style="border-radius: 16px;">
            {% else %}
                <input class="btn btn-primary likeBtn" type="submit" value="Like" style="border-radius: 16px;">
            {% endif %}

            {% if post.user == user %}
                <input class="btn btn-primary editBtn" type="submit" value="Edit" style="border-radius: 16px; position: relative;">
            {% endif %}

            <input type="hidden" class="post-id" value="{{ post.id }}">
        </div>
    {% endfor %}

    <nav aria-label="Posts navigation" style="margin-top: 20px;">
        <ul class="pagination justify-content-center">
            {% if has_prev %}
                <li class="page-item"><a class="page-link" href="{{ prev_num }}">Previous</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#" aria-disabled="true">Previous</a></li>
            {% endif %}
            {% for i in p.page_range %}
                <li class="page-item"><a class="page-link" href="{{i}}">{{i}}</a></li>
            {% endfor %}
            {% if has_next %}
                <li class="page-item"><a class="page-link" href="{{ next_num }}">Next</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#" aria-disabled="true">Next</a></li>
            {% endif %}
        </ul>
      </nav>
      <script src="{% static 'network/posts-index.js' %}"></script>
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'network/style.css' %}" rel="stylesheet">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom: 2%;">
            <a class="navbar-brand" href="#">Network</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:profile' user.username %}"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'network:index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:following' %}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>

{% endblock %}

network/templates/network/profile.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}
{% if user.is_authenticated %}
    <input id="owner-username" type="hidden" value="{{ owner }}">
    <input id="visitor-username" type="hidden" value="{{ visitor }}">

    <div id="profile-header">
        <h2 id="profile-username">{{ owner }}</h2>
        <h5>Followers: <span id="followers-count">{{ followers }}</span></h5>
        <h5>Following: <span id="following-count">{{ following }}</span></h5>

        {% if visitor != owner %}
            {% if isFollower %}
                <input id="follow-btn" class="btn btn-primary" type="submit" value="Unfollow">
            {% else %}
                <input id="follow-btn" class="btn btn-primary" type="submit" value="Follow">
            {% endif %}
        {% endif %}
    </div>

    {% for post in posts %}
        <div class="posts">
            <a href="{% url 'network:profile' post.user %}">{{ post.user }}</a>
            <hr style="margin-top: 0; width: 20%; position: relative; margin-left: 0px;">
            <p class="post-content">{{ post.content }}</p>
            <small>{{ post.date }}</small><br>
            <small><span class="post-likes">{{ post.likes.all.count }}</span> Likes</small><br>

            {% if post.user == user %}
                <input class="btn btn-primary editBtn" type="submit" value="Edit" style="border-radius: 16px; position: relative;">
            {% endif %}

            <input type="hidden" class="post-id" value="{{ post.id }}">
        </div>
    {% endfor %}

    <nav aria-label="Posts navigation" style="margin-top: 20px;">
        <ul class="pagination justify-content-center">
            {% if has_prev %}
                <li class="page-item"><a class="page-link" href="{{ prev_num }}">Previous</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#" aria-disabled="true">Previous</a></li>
            {% endif %}
            {% for i in p.page_range %}
                <li class="page-item"><a class="page-link" href="/profile/{{owner}}/{{i}}">{{i}}</a></li>
            {% endfor %}
            {% if has_next %}
                <li class="page-item"><a class="page-link" href="{{ next_num }}">Next</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#" aria-disabled="true">Next</a></li>
            {% endif %}
        </ul>
    </nav>
{% endif %}
<script src="{% static 'network/posts-profile.js' %}"></script>
<script src="{% static 'network/posts-index.js' %}"></script>
{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>

{% endblock %}